In [ ]:
# numpyの読み込み
import numpy as np

#AとBの行列を定義
arrayA = np.array([[0, 1, ], [2, 3,], [4, 5]])
arrayB = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

#計算結果の表示
seki = np.dot(arrayA,arrayB)
print(seki)

#行列の最大値を求める
seki.max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47